SELECT 
	  '2017-05-24' AS COB_DATE
	, ACC.ACCT_NO
	, F.CUSTOMER AS CIF
	, ISS.CARD_NUM
	, ISS.ISS_DATE
	, ISS.START_DATE
	, ISS.EXPIR_DATE
	, ISS.CRDH_NAME AS CUSTOMER_NAME
	, ISS.CARD_ID
	, ISS.APPLICATION_ID
	, ISS.CARD_CONTRACT
	, CONTRACT.CONTRACT_DESC
	, ISS.CARD_INT_TYPE
	, TP.CARD_TYPE_NAME
	, ISS.ATM_ACCT
	, ISS.POS_ACCT
	, ISS.LIMITS_SCHEME
	, ISS.FEE_SCHEME
	, ISS.ATM_TDY
	, ISS.POS_TDY
	, ISS.AGGREGATE_TDY
	, ISS.CARD_STATUS
	, ISS.CREDIT_LIMIT
	, HIS.DELIVERY_CODE AS BRANCH_CODE
	, F.WORKING_BALANCE AS BALANCE
	, F.AMNT_LAST_DR_CUST
	, F.TRAN_LAST_DR_CUST
	, F.DATE_LAST_DR_CUST
	, F.CURRENCY AS CCY
FROM ISS_CARD_TAB AS ISS
JOIN CARD_ACCT_TAB AS ACC
	ON ISS.CARD_NUM = ACC.CARD_NO
JOIN  ISS_CARDHIST_TAB AS HIS
	ON ISS.CARD_NUM = HIS.CARD_NUM 
JOIN CARD_TYPE AS TP
	ON ISS.CARD_INT_TYPE = TP.CARD_TYPE_ID
JOIN F_ACCOUNT AS F
	ON ACC.ACCT_NO = F.ACCOUNT_NUMBER
JOIN ISS_CARD_CONTRACT_TAB AS CONTRACT
	ON ISS.CARD_CONTRACT = CONTRACT.CONTRACT_ID
WHERE F.DATA_DATETIME = '20170524'

