IF OBJECT_ID('tempdb..#TABLE') IS NOT NULL
	DROP TABLE #TABLE
SELECT COLUMN_NAME, ORDINAL_POSITION
INTO #TABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'F_ACCOUNT' 


IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL
    DROP TABLE #TEMP
CREATE TABLE #TEMP (
	ID int IDENTITY(1,1) PRIMARY KEY,
	ROW_COUNT VARCHAR(100),
	COLUMN_NAME VARCHAR(255)
)

DECLARE @COLUMN_NAME VARCHAR(255)
DECLARE @TABLE_NAME VARCHAR(255)
DECLARE @DATE VARCHAR(8)
DECLARE @COUNT INT
DECLARE @START INT
DECLARE @END INT
SET @TABLE_NAME = 'F_ACCOUNT'
DECLARE @SQL VARCHAR(MAX)
SET @START = 0
SET @END = (SELECT COUNT(1) FROM #TABLE)
SET @DATE = '20170427'


WHILE (@START <= @END)
BEGIN
	SET @START = @START + 1

	--PRINT(@START)
	SELECT @SQL = 'INSERT INTO #TEMP (ROW_COUNT) SELECT TOP 1 CAST(' + COLUMN_NAME + ' AS VARCHAR(100)) TEST FROM ' +  @TABLE_NAME  + ' WHERE ' + COLUMN_NAME + ' IS NOT NULL '--DATA_DATETIME = ' + ''''+  @DATE + ''''
	FROM #TABLE
	WHERE ORDINAL_POSITION = @START
	
	UPDATE A 
	SET A.COLUMN_NAME = B.COLUMN_NAME
	FROM #TABLE AS B, #TEMP AS A 
	WHERE B.ORDINAL_POSITION = A.ID 

	EXEC(@SQL)
	PRINT(@SQL)
	IF @START = @END +1
		BREAK
END;

SELECT * FROM #TEMP
SELECT * FROM #TABLE


