IF OBJECT_ID('tempdb..#TABLE') IS NOT NULL
	DROP TABLE #TABLE
SELECT COLUMN_NAME, ORDINAL_POSITION
INTO #TABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'F_ACCOUNT' 

--SELECT * FROM #TABLE


IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL
    DROP TABLE #TEMP
CREATE TABLE #TEMP (
	ID int IDENTITY(1,1) PRIMARY KEY,
	ROW_COUNT INT,
	COLUMN_NAME VARCHAR(255)
)

DECLARE @COLUMN_NAME VARCHAR(255)
DECLARE @TABLE_NAME VARCHAR(255)
DECLARE @COUNT INT
DECLARE @START INT
DECLARE @END INT
SET @TABLE_NAME = 'F_ACCOUNT'
DECLARE @SQL VARCHAR(MAX)
SET @START = 0
SET @END = (SELECT COUNT(1) FROM #TABLE)
DECLARE @DATE DATE = '20170531'


WHILE (@START <= @END)
BEGIN
	SET @START = @START + 1

	--PRINT(@START)
	SELECT @SQL = 'INSERT INTO #TEMP (ROW_COUNT) SELECT COUNT(' + COLUMN_NAME + ') AS COUNT FROM ' +  @TABLE_NAME  + ' WHERE DATA_DATETIME = ' + '''20170531'''
	FROM #TABLE
	WHERE ORDINAL_POSITION = @START
	
	UPDATE A 
	SET A.COLUMN_NAME = B.COLUMN_NAME
	FROM #TABLE AS B, #TEMP AS A
	WHERE B.ORDINAL_POSITION = A.ID 

	EXEC(@SQL)
	--PRINT(@SQL)
	IF @START = @END +1
		BREAK
END;


SELECT * FROM #TEMP WHERE ROW_COUNT = 0

SELECT  * FROM F_ACCOUNT WHERE DATA_DATETIME = '20170531' AND DATA_DATETIME =  CONVERT(DATE, DATE_TIME)

SELECT TOP 10 * FROM F_ACCOUNT WHERE DATA_DATETIME = '20170531' AND INTEREST_LIQU_ACCT IS NOT NULL

SELECT TOP 10 *
INTO F_ACCOUNT
FROM SV31.STG_T24.DBO.F_ACCOUNT

SELECT * FROM F_ACCOUNT

ALTER TABLE F_ACCOUNT
DROP COLUMN 
			INTEREST_COMP_ACCT,
			INT_NO_BOOKING,
			WAIVE_LEDGER_FEE,
			CAP_BACK_VALUE,
			ACCR_CHG_CATEG,
			ACCR_CHG_TRANS,
			ACCR_CHG_AMOUNT,
			ACCR_CHG_SUSP,
			ACCR_CR_SUSP,
			ACCR_CR2_CATEG,
			ACCR_CR2_TRANS,
			ACCR_CR2_AMOUNT,
			ACCR_CR2_SUSP,
			ACCR_DR_SUSP,
			ACCR_DR2_CATEG,
			ACCR_DR2_TRANS,
			ACCR_DR2_AMOUNT,
			ACCR_DR2_SUSP,
			CONSOL_KEY,
			START_YEAR_BAL,
			CREDIT_MOVEMENT,
			DEBIT_MOVEMENT,
			VALUE_DATED_BAL,
			CONTINGENT_BAL_CR,
			CONTINGENT_BAL_DR,
			OPEN_VAL_DATED_BAL,
			CLOSURE_DATE,
			LOCKED_WITH_LIMIT,
			CHARGE_ACCOUNT,
			CON_CHARGE_ACCR,
			CON_INTEREST_ACCR,
			PREMIUM_TYPE,
			CAP_DATE_PRM,
			PREMIUM_FREQ,
			APR,
			STMT_RECO_WITH,
			RECO_TOLERANCE,
			PENDING_ID,
			TOTAL_PENDING,
			STOCK_CONTROL_TYPE,
			SERIAL_NO_FORMAT,
			AUTO_PAY_ACCT,
			ORIG_CCY_PAYMENT,
			ORIGINAL_ACCT,
			FROM_DATE,
			LOCKED_AMOUNT,
			DISPO_OFFICER,
			DISPO_EXEMPT,
			TAX_SUSPEND,
			TAX_AT_SETTLE,
			ICA_MAIN_ACCOUNT,
			ICA_DISTRIB_RATIO,
			ICA_MAIN_ACCT_IND,
			ICA_DISTRIB_TYPE,
			ICA_POST_INTEREST,
			ICA_MAIN_RATIO,
			ICA_NEW_MAIN_ACC,
			ICA_START_DATE,
			ICA_ADD_REMOVE,
			ICA_BACK_VALUE,
			ICA_MAIN_ACCT,
			ICA_MAIN_DATE,
			LIQUIDATION_MODE,
			ALL_IN_ONE_PRODUCT,
			ER_VALUE_DATE,
			ER_BALANCE,
			EP_BALANCE,
			SB_GROUP_ID,
			CREDIT_CHECK,
			AVAILABLE_BAL_UPD,
			CONSOLIDATE_ENT,
			MAX_SUB_ACCOUNT,
			MASTER_ACCOUNT,
			LOCK_INC_THIS_MVMT,
			NEXT_AF_DATE,
			NEXT_EXP_DATE,
			NEXT_STMT_DATE,
			EXPOSURE_DATES,
			PORTFOLIO_NO,
			SHADOW_ACCOUNT,
			FWD_ENTRY_HOLD,
			CASH_POOL_GROUP,
			OPEN_ASSET_TYPE,
			IC_CHARGE_ID,
			IC_NEXT_CAP_DATE,
			ACC_DEB_LIMIT,
			DR2_ADJ_AMOUNT,
			CR2_ADJ_AMOUNT,
			RECORD_STATUS,
			AUDITOR_CODE,
			AUDIT_DATE_TIME,
			ACCOUNT_STATUS,
			CR_MARGIN_RATE,
			OD_STATUS

