--Deposit
select L.CONTRACT_NO
	, L.CIF
	, X.NAME_1
	, X.LEGAL_ID
	, X.LEGAL_DOC_NAME
	, X.LEGAL_HOLDER_NAME
	, L.BRANCH_CODE
	, BRANCH_NAME
	, L.SEGMENT
	, L.APP
	, L.CATEGORY
	, L.SUB_CATEGORY
	, P.PRODUCT_SEGMENT
	, P.PRODUCT_GROUP
	, P.PRODUCT_SUB_GROUP
	, L.VALUE_DATE
	, L.MATURITY_DATE
	, L.INTEREST_RATE
	, X.DATE_OF_BIRTH
	, X.PHONE_NUMBER
	, X.EMAIL
	, X.STREET
	, X.ADDRESS
	, X.AGE
INTO PVCOM..DEPOSIT_CUSTOMER_18_24
from MasterDeposit L
left join (
	SELECT CUSTOMER_CODE
		, NAME_1
		, STREET
		, ADDRESS
		, TOWN_COUNTRY
		, GENDER
		, DATE_OF_BIRTH
		, LEGAL_ID
		, LEGAL_HOLDER_NAME
		, LEGAL_DOC_NAME
		, PHONE_NUMBER
		, EMAIL
		, DATEDIFF(YEAR, DATE_OF_BIRTH, GETDATE()) AS AGE
	FROM DIMCUSTOMER
	WHERE TARGET = 4000
) AS X ON l.CIF = X.CUSTOMER_CODE
LEFT JOIN (
	SELECT * 
	FROM DimProduct 
	WHERE PRODUCT_KEY = 'DEPOSIT' AND SEGMENT = 'KHCN'
) AS P
ON L.SUB_CATEGORY = P.SUB_CATEGORY
WHERE X.AGE BETWEEN 18 AND 24 AND L.FLAG IS NULL
ORDER BY NAME_1

--Loan
select L.COMMITMENT_NO
	, L.CONTRACT_NO
	, L.CIF
	, X.NAME_1
	, X.LEGAL_ID
	, X.LEGAL_DOC_NAME
	, X.LEGAL_HOLDER_NAME
	, L.BRANCH_CODE
	, BRANCH_NAME
	, L.SEGMENT_CODE
	, L.SEGMENT
	, L.APP
	, L.CATEGORY
	, L.SUB_CATEGORY
	, L.PRODUCT_SEGMENT
	, L.PRODUCT_GROUP
	, L.PRODUCT_SUB_GROUP
	, L.VALUE_DATE
	, L.MATURITY_DATE
	, L.TERM
	, L.INTEREST_RATE
	, L.PR_AMT
	, X.DATE_OF_BIRTH
	, X.PHONE_NUMBER
	, X.EMAIL
	, X.STREET
	, X.ADDRESS
from MasterLoan L
left join (
	SELECT CUSTOMER_CODE
		, NAME_1
		, STREET
		, ADDRESS
		, TOWN_COUNTRY
		, GENDER
		, DATE_OF_BIRTH
		, LEGAL_ID
		, LEGAL_HOLDER_NAME
		, LEGAL_DOC_NAME
		, PHONE_NUMBER
		, EMAIL
		, DATEDIFF(YEAR, DATE_OF_BIRTH, GETDATE()) AS AGE
	FROM DIMCUSTOMER
	WHERE TARGET = 4000
) AS X ON l.CIF = X.CUSTOMER_CODE
WHERE X.AGE BETWEEN 18 AND 24 AND L.FLAG IS NULL


-- CARD
SELECT C.CARD_ID
	, C.CARD_NUM
	, C.ACCTNO
	, C.CIF
	, X.NAME_1
	, X.LEGAL_ID
	, X.LEGAL_DOC_NAME
	, X.LEGAL_HOLDER_NAME
	, C.BRANCH_CODE
	, C.CARD_TYPE_ID
	, C.CARD_CONTRACT_ID
	, C.ISSUE_DATE
	, C.ACTIVATION_DATE
	, C.EXPIRY_DATE
	, C.CARD_STATUS
	, x.STREET
	, X.ADDRESS
	, X.DATE_OF_BIRTH
	, x.PHONE_NUMBER
	, x.EMAIL
	, x.AGE
INTO PVCOM..CARD_CUSTOMER_18_24
FROM MasterCard AS C
LEFT JOIN(
	SELECT CUSTOMER_CODE
		, NAME_1
		, STREET
		, ADDRESS
		, TOWN_COUNTRY
		, GENDER
		, DATE_OF_BIRTH
		, LEGAL_ID
		, LEGAL_HOLDER_NAME
		, LEGAL_DOC_NAME
		, PHONE_NUMBER
		, EMAIL
		, DATEDIFF(YEAR, DATE_OF_BIRTH, GETDATE()) AS AGE
	FROM DIMCUSTOMER
	WHERE TARGET = 4000
) AS X ON C.CIF = CONVERT(VARCHAR(15), X.CUSTOMER_CODE)
WHERE X.AGE BETWEEN 18 AND 24

