DECLARE @START_DATE DATE = '20170101'
DECLARE @END_DATE DATE = '20271231'

IF OBJECT_ID('tempdb..#TempCalendar') IS NOT NULL
    DROP TABLE #TempCalendar

CREATE TABLE #TempCalendar (
	  ID int IDENTITY(1,1) PRIMARY KEY
	, FULL_DATE DATE
	, DAY_OF_WEEK VARCHAR(12)
	, DAY_OF_MONTH INT
	, DAY_OF_YEAR INT
	, WEEK_OF_MONTH INT
	, WEEK_OF_YEAR INT
	, MONTH_OF_YEAR INT
	, FLAG INT
)

BEGIN

	WHILE @START_DATE <= @END_DATE
		BEGIN
			INSERT INTO #TempCalendar(FULL_DATE)
			SELECT @START_DATE
			------------------------------------
			IF @START_DATE = @END_DATE
				BREAK
			SET @START_DATE = DATEADD(DAY, 1, @START_DATE )
			
		END

	-- UPDATE DAY_OF_MONTH
	UPDATE tmp
		SET DAY_OF_MONTH = CONVERT(INT, RIGHT(tmp.FULL_DATE, 2))
		, MONTH_OF_YEAR = CONVERT(INT, SUBSTRING(CONVERT(VARCHAR(8), FULL_DATE, 112), 5, 2))
	FROM #TempCalendar AS tmp

	--UPDATE DAY_OF_WEEK, DAY_OF_YEAR
	BEGIN
		WITH X AS (
			SELECT   FULL_DATE
					, ROW_NUMBER() OVER(PARTITION BY (LEFT(FULL_DATE, 4)) ORDER BY FULL_DATE) AS RN
			FROM #TempCalendar
		)
		UPDATE temp
		SET   temp.DAY_OF_YEAR = X.RN
			, temp.DAY_OF_WEEK = DATENAME(dw,x.FULL_DATE)
			, temp.WEEK_OF_YEAR = DatePart(week, x.FULL_DATE)
			, temp.WEEK_OF_MONTH = DATEDIFF(WEEK, DATEADD(MONTH, DATEDIFF(MONTH, 0, x.FULL_DATE), 0), x.FULL_DATE) +1
		FROM #TempCalendar AS temp, X
		WHERE temp.FULL_DATE = X.FULL_DATE
	END

	--update holiday
	UPDATE #TempCalendar
		SET FLAG = 1
	WHERE FULL_DATE LIKE '2017%'

	update #TempCalendar
		SET FLAG = 0
	WHERE FULL_DATE LIKE '2017%' AND ( FULL_DATE IN (  '2017-01-01'
						, '2017-01-02'
						, '2017-01-26'
						, '2017-01-27'
						, '2017-01-28'
						, '2017-01-29'
						, '2017-01-30'
						, '2017-01-31'
						, '2017-02-01'
						, '2017-04-06'
						, '2017-04-07'
						, '2017-04-30'	
						, '2017-05-01'
						, '2017-05-02'
						, '2017-09-02'
						, '2017-04-09')  OR DAY_OF_WEEK = 'Sunday')
END

CREATE TABLE DimCalendar (
	  ID int IDENTITY(1,1) PRIMARY KEY
	, FULL_DATE DATE
	, DAY_OF_WEEK VARCHAR(12)
	, DAY_OF_MONTH INT
	, DAY_OF_YEAR INT
	, WEEK_OF_MONTH INT
	, WEEK_OF_YEAR INT
	, MONTH_OF_YEAR INT
	, FLAG INT
)

insert into DimCalendar(
	FULL_DATE
	, DAY_OF_WEEK
	, DAY_OF_MONTH
	, DAY_OF_YEAR
	, WEEK_OF_MONTH
	, WEEK_OF_YEAR
	, MONTH_OF_YEAR
	, FLAG
) SELECT FULL_DATE
	, DAY_OF_WEEK
	, DAY_OF_MONTH
	, DAY_OF_YEAR
	, WEEK_OF_MONTH
	, WEEK_OF_YEAR
	, MONTH_OF_YEAR
	, FLAG
FROM #TempCalendar

SELECT * FROM DimCalendar








