SELECT  CREDIT_LINE_NO
		,  CREDIT_LINE
		,  LIABILITY_NUMBER
		,  RECORD_PARENT
		,  CO_CODE
		,  LIMIT_CURRENCY
		,  APPROVAL_DATE
		,  OFFERED_UNTIL
		,  REVIEW_FREQUENCY
		,  EXPIRY_DATE
		,  ADM_EXTENSION_DATE
		,  PROPOSAL_DATE
		,  ONLINE_LIMIT_DATE
		,  INTERNAL_AMOUNT
		,  ADVISED_AMOUNT
		,  FIXED_VARIABLE
		,  MAXIMUM_UNSECURED
		,  MAXIMUM_TOTAL
		,  OTHER_SECURED
		,  DATE_LAST_REVAL
		,  ORIGINAL_LIMIT
		,  AVAILABLE_MARKER
		,  REDUCING_LIMIT
		,  FX_OR_TIME_BAND
		,  CHECK_LIMIT
		,  LIMIT_PRODUCT
		,  ALLOW_NETTING
		,  ONLINE_UPDATE
		,  LAST_DRAW_DATE
		,  ALLOC_WORK_ID
		,  OVERRIDE
		,  CURR_NO
		,  INPUTTER
		,  DATE_TIME
		,  AUTHORISER
		,  DEPT_CODE
		,  CURR
		,  EFFECTIVE_FROM_DATETIME
		,  EFFECTIVE_TO_DATETIME
		,  DATE_TIME2
FROM F_LIMIT
WHERE CREDIT_LINE_NO IN ('10000006.0010000.01', '10000006.0009200.01')
ORDER BY CREDIT_LINE_NO

SELECT DISTINCT CO_CODE FROM F_LIMIT
SELECT * FROM PVCom..DimBranch WHERE BRANCH_CODE = 'VN0010001'
SELECT * FROM F_LIMIT_REFERENCE

SELECT * FROM F_LIMIT_ACC_COMPANY WHERE EFFECTIVE_FROM_DATETIME  = '20170217'

