SELECT X.CONTRACT_NO_
	, X.OUR_REFERENCE
	, X.CO_CODE 
	, X.BRANCH_NAME
	, X.CUSTOMER_ID
	, X.TEN_KH
	, X.TARGET 
	, X.COMMITMENT_NO
	, X.CATEGORY_CODE
	, X.CATEGORY_NAME
	, X.CURRENCY
	, X.RATE
	, X.TRANSACTION_CODE
	, SUM (X.AMOUNT_LCY) AS AMOUNT_LCY
INTO #TEMP
FROM (

	SELECT LD.CONTRACT_NO_
		, STMT.OUR_REFERENCE
		, LD.CO_CODE 
		, DB.BRANCH_NAME
		, LD.CUSTOMER_ID
		, ISNULL(DC.NAME_1, '') + ISNULL(DC.NAME_2, '') as TEN_KH
		, DC.TARGET 
		, LD.COMMITMENT_NO
		, LD.CATEGORY AS CATEGORY_CODE
		, Categ.CATEGORY_NAME
		, LD.CURRENCY
		, CCY.MID_REVAL_RATE AS RATE
		, STMT.TRANSACTION_CODE
		, STMT.AMOUNT_LCY
	
	FROM F_LD_LOANS_AND_DEPOSITS AS LD
	JOIN DIMBRANCH AS DB
		ON LD.CO_CODE = DB.BRANCH_CODE
	JOIN PVCom..DimCustomer AS DC
		ON LD.CUSTOMER_ID = DC.CUSTOMER_CODE
	JOIN PVCom..DimCategory Categ
		ON LD.CATEGORY = Categ.CATEGORY_CODE
	JOIN F_CURRENCY_CURRENCY_MARKET AS CCY
		ON LD.CURRENCY = CCY.CURRENCY_CODE
	JOIN F_STMT_ENTRY AS STMT
		ON STMT.OUR_REFERENCE  = LD.CONTRACT_NO_
	where LD.DATA_DATETIME = '20170427'
		AND STMT.BOOKING_DATE = '20170427'
		AND CCY.DATA_DATETIME = '20170427' 
		AND CCY.CURRENCY_MARKET = '1'
) X
GROUP BY X.CONTRACT_NO_
	, X.OUR_REFERENCE
	, X.CO_CODE 
	, X.BRANCH_NAME
	, X.CUSTOMER_ID
	, X.TEN_KH
	, X.TARGET 
	, X.COMMITMENT_NO
	, X.CATEGORY_CODE
	, X.CATEGORY_NAME
	, X.CURRENCY
	, X.RATE
	, X.TRANSACTION_CODE



SELECT * FROM #TEMP

select * from PVCom..DimCustomer where 


SELECT *
FROM PVCom..DimCustomer
WHERE CUSTOMER_CODE IN ('10395331','10394983','10395078','10395032','10395199','10395234','10395204','10395350')





	SELECT TOP 10 TARGET,  * FROM PVCom..DimCustomer
	SELECT TOP 1000 VALUE_DATE, FIN_MAT_DATE, * FROM F_LD_LOANS_AND_DEPOSITS WHERE ASSET_CLASS IS NOT NULL
	SELECT TOP 10 * FROM PVCom..DimCategory
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'F_LD_LOANS_AND_DEPOSITS'
	select * from PVCom..DimTerm

	SELECT TOP 1000 TRANSACTION_CODE, OUR_REFERENCE, AMOUNT_FCY, AMOUNT_DEAL_CCY, AMOUNT_LCY, * 
	FROM F_STMT_ENTRY 
	WHERE BOOKING_DATE = '20170426' AND TRANSACTION_CODE = '860' AND STMT_ENTRY_ID = '180149347450616.030001'

	SELECT TOP 10 * FROM F_LD_LOANS_AND_DEPOSITS WHERE DATA_DATETIME = '20170426' AND CONTRACT_NO_ = 'LD1704713086'

	SELECT  * FROM F_CURRENCY_CURRENCY_MARKET WHERE DATA_DATETIME = '20170426' ORDER BY CURRENCY_CODE


	SELECT  * FROM F_ACCOUNT WHERE DATA_DATETIME = '20170426' AND ACCOUNT_NUMBER = '108000296240'
	
	SELECT * FROM PVCom..DimCustomer WHERE CUSTOMER_CODE = '10343407'

	SELECT * FROM PVCom..DimCustomerClass

	SELECT DISTINCT TRANSACTION_CODE FROM F_STMT_ENTRY WHERE BOOKING_DATE = '20170427' ORDER BY TRANSACTION_CODE

	SELECT * FROM F_TRANSACTION_NARRATIVE WHERE NARRATIVE LIKE '% Penalty%'

select * from F_LIMIT



	