-- DROP PARTITION FUNCTION OR SCHEME
DROP PARTITION FUNCTION PT_COB_DATE 
DROP PARTITION SCHEME PT_SCHEME_COB_DATE

--CREATE PARTITION FUNCTION
DECLARE @PT_DATETIME NVARCHAR(MAX) = 
    N'CREATE PARTITION FUNCTION PT_COB_DATE (DATE) 
    AS RANGE RIGHT FOR VALUES (';  
DECLARE @START DATE = '20150101';  
DECLARE @END DATE = '20300101';  


WHILE @START < @END 
BEGIN  
		SET @PT_DATETIME += '''' + CAST(@START AS NVARCHAR(10)) + '''' + N', ';  
		SET @START = DATEADD(DAY, 1, @START);  
		IF @START = @END
			BREAK
END  

SET @PT_DATETIME += '''' + CAST(@START AS NVARCHAR(10))+ '''' + N');'; 

EXEC SP_EXECUTESQL @PT_DATETIME;  
GO  


--CREATE PARTITION SCHEMA
CREATE PARTITION SCHEME PT_SCHEME_COB_DATE  
AS PARTITION PT_COB_DATE  
ALL TO ( [PRIMARY] ); 


-- CREATE PARTITION SCHEME FOR TABLE
CREATE INDEX PK_FactLoanNew
  ON factloan (COB_DATE)
  WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
         ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
  ON PT_SCHEME_COB_DATE(COB_DATE)

-- CHECK PARTITION FOR TABLE
SELECT O.NAME OBJECTNAME,I.NAME INDEXNAME, PARTITION_ID, PARTITION_NUMBER, [ROWS]
FROM SYS.PARTITIONS P 
--INNER JOIN SYS.PARTITION_RANGE_VALUES PV ON P.partition_id = PV.
INNER JOIN SYS.OBJECTS O ON O.OBJECT_ID=P.OBJECT_ID
INNER JOIN SYS.INDEXES I ON I.OBJECT_ID=P.OBJECT_ID AND P.INDEX_ID=I.INDEX_ID
WHERE O.NAME LIKE '%FACTLOAN%'



-- CHECK PARTITION FOR DATABASE
SELECT 
    OBJECT_SCHEMA_NAME(I.OBJECT_ID) AS [SCHEMA],
    OBJECT_NAME(I.OBJECT_ID) AS [OBJECT_NAME],
    T.NAME AS [TABLE_NAME],
    I.NAME AS [INDEX_NAME],
    S.NAME AS [PARTITION_SCHEME]
FROM SYS.INDEXES I
    JOIN SYS.PARTITION_SCHEMES S ON I.DATA_SPACE_ID = S.DATA_SPACE_ID
    JOIN SYS.TABLES T ON I.OBJECT_ID = T.OBJECT_ID  

-- CHECK PARTITON RANGE VALUES
SELECT * FROM SYS.PARTITION_RANGE_VALUES


ALTER TABLE factloan ADD CONSTRAINT [PK_COB_DATE] PRIMARY KEY CLUSTERED 
(
  COB_DATE
) ON PT_SCHEME_COB_DATE(COB_DATE);


ALTER TABLE FACTLOAN
ADD CONSTRAINT PK_COB_DATE PRIMARY KEY (CONTRACT_NO);

ALTER TABLE FACTLOAN
ADD PRIMARY KEY (CONTRACT_NO);


ALTER TABLE PVCOM..FACTLOAN
ADD FOREIGN KEY (COB_DATE) REFERENCES PVCOM..FACTLOAN(contract_no)

ALTER TABLE factloan ADD PRIMARY KEY(cob_date, contract_no);

ALTER TABLE factloan DROP PRIMARY KEY

