DECLARE @START_DATE DATE = '20170617'
DECLARE @END_DATE DATE = '20170619'

DECLARE @COB_DATE DATE
DECLARE @NEXT_COB_DATE DATE

IF OBJECT_ID('tempdb..#TEMP') is not null
	DROP TABLE #TEMP

CREATE TABLE #TEMP (
	ID int IDENTITY(1,1) PRIMARY KEY,
	COB_DATE DATE
)


IF (DATEDIFF(DAY, @START_DATE, @END_DATE)) >= 1
BEGIN
	WHILE (@START_DATE <= @END_DATE)
	BEGIN
		
		INSERT INTO #TEMP (COB_DATE)
		VALUES (@START_DATE)

		SET @START_DATE =  DATEADD(DAY, 1, @START_DATE)
		IF (@START_DATE > @END_DATE)
			BREAK

	END

	SET @COB_DATE = (SELECT MIN(COB_DATE) FROM #TEMP)
	SET @NEXT_COB_DATE = (SELECT MAX(COB_DATE) FROM #TEMP)

	WHILE (@COB_DATE <= @NEXT_COB_DATE)
	BEGIN
		IF (@COB_DATE < @NEXT_COB_DATE) 
			INSERT INTO FACTAvgDeposit
			(
				  COB_DATE
				, CONTRACT_NO
				, APP
				, CIF 
				, CUST_CLASS 
				, CUST_CLASS_NOTE
				, SEGMENT 
				, SUB_SEGMENT 
				, CCY 
				, CATEGORY
				, SUB_CATEGORY
				, PRODUCT_SEGMENT
				, PRODUCT_GROUP
				, PRODUCT_SUB_GROUP
				, CUST_GROUP
				, CUST_SUBGROUP
				, BRANCH_CODE
				, BRANCH_NAME
				, REGION
				, DEPT_CODE
				, DEPT_NAME
				, INTEREST_RATE
				, VALUE_DATE
				, MATURITY_DATE
				, TERM
				, FLAG
				, FCY_BAL
				, LCY_BAL
			)
			SELECT 
				 DATEADD(DAY, 1, @COB_DATE) AS COB_DATE
				, CONTRACT_NO
				, APP
				, CIF 
				, CUST_CLASS 
				, CUST_CLASS_NOTE
				, SEGMENT 
				, SUB_SEGMENT 
				, CCY 
				, CATEGORY
				, SUB_CATEGORY
				, PRODUCT_SEGMENT
				, PRODUCT_GROUP
				, PRODUCT_SUB_GROUP
				, CUST_GROUP
				, CUST_SUBGROUP
				, BRANCH_CODE
				, BRANCH_NAME
				, REGION
				, DEPT_CODE
				, DEPT_NAME
				, INTEREST_RATE
				, VALUE_DATE
				, MATURITY_DATE
				, TERM
				, FLAG
				, FCY_BAL
				, LCY_BAL
			FROM FACTAvgDeposit
			WHERE COB_DATE = @COB_DATE
		ELSE 
			EXEC PCD_FactAvgDeposit @NEXT_COB_DATE


		SET @COB_DATE = DATEADD(DAY, 1, @COB_DATE)
		IF(@COB_DATE >= @NEXT_COB_DATE)
			BREAK
	END
END
