
	DECLARE @DATE DATE = '20170529'
	IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL
	DROP TABLE #TEMP

	SELECT *
	INTO #TEMP
	FROM 
	(

	-- SAVING BOOKS:
	SELECT A.COB_DATE
		, A.ARRANGEMENT_ID
		, B.ACCOUNT_NO
		, A.CIF
		, 'NULL' AS CUSTOMER_GROUP
		, A.CCY
		, B.CATEGORY
		, B.CURRENCY_MARKET
		, A.BRANCH_CODE
		, LTRIM(RTRIM(D.BRANCH_NAME)) AS BRANCH_NAME
		, A.VALUE_DATE
		, NULL AS MATURITY_DATE
		, C.BALANCE
		, DT.RENEWAL_DATE
	FROM
	(
		SELECT DATA_DATETIME AS COB_DATE
			, ARRANGEMENT_ID
			, CUSTOMER AS CIF
			, CURRENCY AS CCY
			, CO_CODE AS BRANCH_CODE
			, ARR_STATUS
			, START_DATE AS VALUE_DATE
			, PRODUCT_LINE
			, PRODUCT_GROUP
			, INTEREST_RATE
		FROM STG_T24.dbo.F_AA_ARRANGEMENT
		WHERE DATA_DATETIME = @DATE
			AND ARR_STATUS <> 'CLOSE'
			AND START_DATE = @DATE
	) A
	LEFT JOIN 
	(
		SELECT DISTINCT ID_COMP_1 AS ARRANGEMENT_ID
			, CATEGORY
			, SHORT_TITLE
			, ACCOUNT_REFERENCE AS ACCOUNT_NO
			, PASSBOOK
			, CURRENCY_MARKET
			, DEPT_CODE
		FROM STG_T24.dbo.F_AA_ARR_ACCOUNT
		WHERE DATA_DATETIME = @DATE
	) B ON A.ARRANGEMENT_ID = B.ARRANGEMENT_ID
	LEFT JOIN
	(
		SELECT DISTINCT LEFT(PROPERTY_NAME, CHARINDEX('-', PROPERTY_NAME, 1) - 1) AS ARRANGEMENT_ID
			, BALANCE
			, ACCRUAL_AMT
			, BASIS
		FROM STG_T24.dbo.F_AA_INTEREST_ACCRUALS
		WHERE DATA_DATETIME = @DATE
			AND TO_DATE = DATA_DATETIME
	) C ON A.ARRANGEMENT_ID = C.ARRANGEMENT_ID
	LEFT JOIN STG_T24.dbo.DIMBRANCH D ON A.BRANCH_CODE = D.BRANCH_CODE
	LEFT JOIN 
	(
		SELECT ARRANGEMENT_ID
			, RENEWAL_DATE
		FROM STG_T24..F_AA_ACCOUNT_DETAILS
		WHERE EFFECTIVE_FROM_DATETIME <= @DATE AND ISNULL(EFFECTIVE_TO_DATETIME, '20990101') > @DATE
	) DT ON A.ARRANGEMENT_ID = DT.ARRANGEMENT_ID
	WHERE D.REGION = 'HCM'

	UNION

	-- SAVING WITH PREPAID INTEREST
	

	SELECT X.COB_DATE 
		, X.CONTRACT_NO
		, X.ACCOUNT_NO
		, X.CIF
		, 'NULL' AS CUSTOMER_GROUP
		, X.CCY
		, X.CATEGORY
		, X.CURRENCY_MARKET
		, X.BRANCH_CODE
		, Y.BRANCH_NAME
		, X.VALUE_DATE
		, X.MATURITY_DATE
		, X.BALANCE
		, VW.RENEWAL_DATE 
	
	FROM (
		SELECT DATA_DATETIME AS COB_DATE 
			, CONTRACT_NO_ AS CONTRACT_NO
			, DRAWDOWN_ACCOUNT AS ACCOUNT_NO
			, CUSTOMER_ID AS CIF
			, 'NULL' AS CUSTOMER_GROUP
			, CURRENCY AS CCY
			, CATEGORY
			, CURRENCY_MARKET
			, CO_CODE AS BRANCH_CODE
		--	, BRANCH_NAME
			, VALUE_DATE
			, FIN_MAT_DATE AS MATURITY_DATE
			, DRAWDOWN_ISSUE_PRC AS BALANCE
		FROM STG_T24.dbo.F_LD_LOANS_AND_DEPOSITS
		WHERE DATA_DATETIME = @DATE
	
	) X
	LEFT JOIN 
	(
		SELECT CONTRACT_NO_
			, RENEWAL_DATE
		FROM STG_T24..VW_LD_RENEWAL_NUMBER
		WHERE DATA_DATETIME = @DATE
	) VW ON X.CONTRACT_NO = VW.CONTRACT_NO_

	LEFT JOIN STG_T24.dbo.DIMBRANCH Y ON X.BRANCH_CODE = Y.BRANCH_CODE

	WHERE COB_DATE = @DATE
		AND CATEGORY IN ('21002', '21003')
		AND VALUE_DATE = @DATE
		AND Y.REGION = 'HCM'

	UNION

	---ONLINE SAVING ACCOUNTS:
	----DECLARE @DATE DATE = '20170410'
	-- Tiết kiệm tích luỹ
	SELECT DATA_DATETIME AS COB_DATE 
		, NULL AS ARRANGEMENT_ID
		, ACCOUNT_NUMBER AS ACCOUNT_NO
		, CUSTOMER
		, 'NULL' AS CUSTOMER_GROUP
		, CURRENCY AS CCY
		, CATEGORY
		, CURRENCY_MARKET
		, CO_CODE AS BRANCH_CODE
		, BRANCH_NAME
		, OPENING_DATE AS VALUE_DATE -- value date or open_date of the saving account
		, NULL AS MATURITY_DATE
		, ONLINE_ACTUAL_BAL AS BALANCE
		, NULL AS RENEWAL_DATE
	FROM STG_T24.dbo.F_ACCOUNT X
	LEFT JOIN STG_T24.dbo.DIMBRANCH Y ON X.CO_CODE = Y.BRANCH_CODE
	WHERE DATA_DATETIME = @DATE
		AND CATEGORY = '6602'
		AND OPENING_DATE = @DATE
		AND Y.REGION = 'HCM'
	) A


	UPDATE #TEMP
	SET BALANCE = BALANCE * X.RATE
	FROM 
	(
	SELECT CURRENCY_CODE
		, IIF(CURRENCY_CODE = 'VND', 1, MID_REVAL_RATE) AS RATE
	FROM STG_T24..F_CURRENCY_CURRENCY_MARKET 
	WHERE DATA_DATETIME = @DATE
	) X
	WHERE CCY = X.CURRENCY_CODE


	UPDATE A
	SET A.CUSTOMER_GROUP = C.SEGMENT
	FROM #TEMP A	
		LEFT JOIN 
			(
				SELECT CUSTOMER_CODE
					, [TARGET]
				FROM PVCom..DimCustomer
			) B ON A.CIF = B.CUSTOMER_CODE
		LEFT JOIN DimSegment C ON B.TARGET = C.TARGET_CODE
	WHERE C.SEGMENT IN ('KHCN', 'KHDN')

	SELECT COB_DATE
		, ARRANGEMENT_ID
		, ACCOUNT_NO
		, CIF
		, CUSTOMER_GROUP
		, CCY
		, CATEGORY
		, CURRENCY_MARKET
		, BRANCH_CODE
		, LTRIM(RTRIM(BRANCH_NAME)) AS BRANCH_NAME
		, VALUE_DATE
		, MATURITY_DATE
		, BALANCE 
		, RENEWAL_DATE
	FROM #TEMP
	WHERE CUSTOMER_GROUP IN ('KHCN', 'KHDN') 